spring:
  application:
    name: springboot-devops-app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: ankit
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  # You can change the port or leave default 8080
  port: 8080
