spring:
  application:
    name: springboot-devops-app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: ${SERVER_PORT:8080}
